### ISSUE TITLE
polkadot-worker errors `Cannot convert`

### ISSUE THREAD

**Issue by traumschule** [Joystream/atlas#3678]
What do these mean?

> Uncaught (in promise) Error: Cannot convert 'Ready' via asFuture
>    at polkadot-worker-e3e9fb43.js:1:157224

> polkadot-worker-e3e9fb43.js:1 Uncaught (in promise) Error: Cannot convert 'Broadcast' via asFuture
>    at polkadot-worker-e3e9fb43.js:1:157224

> Uncaught (in promise) Error: Cannot convert 'Normal' via asOperational
>    at polkadot-worker-e3e9fb43.js:1:157224

(seen in chromium)

It's unclear if they can be ignored or if GW OP / DWGL have to act.

Please catch and replace with more meaningful message.

**Comment by dmtrjsg** [comment]
@traumschule  This one is virtually unfixable, tried so many times.. Do you have an idea?

**Comment by traumschule** [comment]
Is it related to #3065?
