### ISSUE TITLE
[Wallet] Catch pending authorization request

### ISSUE THREAD

**Issue by traumschule** [Joystream/atlas#4355]
Looks like this should be silently caught until user authorized the page to access the extension.
```
Failed to enable selected wallet: Timed out in retrying the promise 
Uncaught (in promise) AuthError: The source https://l1.media/video/23003 has a pending authorization request
    at new AuthError (VideoView.styles-500c9df3.js:2434:640)
    at BaseDotsamaWallet.transformError (VideoView.styles-500c9df3.js:2434:992)
    at PolkadotjsWallet.<anonymous> (VideoView.styles-500c9df3.js:2434:1639)
    at Generator.throw (<anonymous>)
    at at (VideoView.styles-500c9df3.js:2434:238)
```

**Comment by dmtrjsg** [comment]
~We are not sure what you want us to do here.. @traumschule can you elaborate pls what's the impact of this and steps to reproduce?~

Thanks for raising we found a bug in the respective function and will fix it. THere's no impact on the user so this will be a low-prio.
